/* Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved. */
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if __has_include("amdmlss/amdmlss_build_config.h")
#include "amdmlss/amdmlss_build_config.h"
#elif __has_include("amdmlss_build_config.h")
#include "amdmlss_build_config.h"
#else
#ifndef MLSS_PLATFORM_WINDOWS
#define MLSS_PLATFORM_WINDOWS 0
#endif
#ifndef MLSS_PLATFORM_LINUX
#define MLSS_PLATFORM_LINUX 0
#endif
#endif

#define MLSS(x) "MLSS_" #x
#define MLSS_GFX(name) "MLSS_GFX" #name

#define MLSS_END_LIST "end"

// Operations
#define MLSS_GQA MLSS(GQA)
#define MLSS_MHA MLSS(MHA)
#define MLSS_GEMM MLSS(GEMM)
#define MLSS_QGEMM MLSS(QGEMM)
#define MLSS_MVN MLSS(MVN)
#define MLSS_CONV MLSS(CONV)
#define MLSS_CONV_DILATED MLSS(CONV_DILATED)
#define MLSS_CONV_DEPTHWISE MLSS(CONV_DEPTHWISE)
#define MLSS_RMSNORM MLSS(RMSNORM)
#define MLSS_SIGMOID_MUL MLSS(SIGMOID_MUL)
#define MLSS_GEMMGEMM MLSS(GEMMGEMM)

// GPU Architectures
#define MLSS_GFX600 MLSS_GFX(600)
#define MLSS_GFX601 MLSS_GFX(601)
#define MLSS_GFX602 MLSS_GFX(602)
#define MLSS_GFX700 MLSS_GFX(700)
#define MLSS_GFX701 MLSS_GFX(701)
#define MLSS_GFX702 MLSS_GFX(702)
#define MLSS_GFX703 MLSS_GFX(703)
#define MLSS_GFX704 MLSS_GFX(704)
#define MLSS_GFX705 MLSS_GFX(705)
#define MLSS_GFX750 MLSS_GFX(750)
#define MLSS_GFX801 MLSS_GFX(801)
#define MLSS_GFX802 MLSS_GFX(802)
#define MLSS_GFX803 MLSS_GFX(803)
#define MLSS_GFX805 MLSS_GFX(805)
#define MLSS_GFX810 MLSS_GFX(810)
#define MLSS_GFX900 MLSS_GFX(900)
#define MLSS_GFX902 MLSS_GFX(902)
#define MLSS_GFX904 MLSS_GFX(904)
#define MLSS_GFX905 MLSS_GFX(905)
#define MLSS_GFX906 MLSS_GFX(906)
#define MLSS_GFX907 MLSS_GFX(907)
#define MLSS_GFX908 MLSS_GFX(908)
#define MLSS_GFX909 MLSS_GFX(909)
#define MLSS_GFX90A MLSS_GFX(90A)
#define MLSS_GFX90C MLSS_GFX(90C)
#define MLSS_GFX940 MLSS_GFX(940)
#define MLSS_GFX941 MLSS_GFX(941)
#define MLSS_GFX942 MLSS_GFX(942)
#define MLSS_GFX950 MLSS_GFX(950)
#define MLSS_GFX1000 MLSS_GFX(1000)
#define MLSS_GFX1010 MLSS_GFX(1010)
#define MLSS_GFX1011 MLSS_GFX(1011)
#define MLSS_GFX1012 MLSS_GFX(1012)
#define MLSS_GFX1013 MLSS_GFX(1013)
#define MLSS_GFX1020 MLSS_GFX(1020)
#define MLSS_GFX1030 MLSS_GFX(1030)
#define MLSS_GFX1031 MLSS_GFX(1031)
#define MLSS_GFX1032 MLSS_GFX(1032)
#define MLSS_GFX1034 MLSS_GFX(1034)
#define MLSS_GFX1035 MLSS_GFX(1035)
#define MLSS_GFX1036 MLSS_GFX(1036)
#define MLSS_GFX1050 MLSS_GFX(1050)
#define MLSS_GFX1100 MLSS_GFX(1100)
#define MLSS_GFX1101 MLSS_GFX(1101)
#define MLSS_GFX1102 MLSS_GFX(1102)
#define MLSS_GFX1103 MLSS_GFX(1103)
#define MLSS_GFX1105 MLSS_GFX(1105)
#define MLSS_GFX1150 MLSS_GFX(1150)
#define MLSS_GFX1151 MLSS_GFX(1151)
#define MLSS_GFX1152 MLSS_GFX(1152)
#define MLSS_GFX1153 MLSS_GFX(1153)
#define MLSS_GFX1154 MLSS_GFX(1154)
#define MLSS_GFX115FFFF MLSS_GFX(115FFFF)
#define MLSS_GFX115FFFE MLSS_GFX(115FFFE)
#define MLSS_GFX1170 MLSS_GFX(1170)
#define MLSS_GFX1171 MLSS_GFX(1171)
#define MLSS_GFX1200 MLSS_GFX(1200)
#define MLSS_GFX1201 MLSS_GFX(1201)
#define MLSS_GFX1210 MLSS_GFX(1210)
#define MLSS_GFX1211 MLSS_GFX(1211)
#define MLSS_GFX120FFFF MLSS_GFX(120FFFF)
#define MLSS_GFX120FFFE MLSS_GFX(120FFFE)
#define MLSS_GFX1250 MLSS_GFX(1250)
#define MLSS_GFX1251 MLSS_GFX(1251)
#define MLSS_GFX1260 MLSS_GFX(1260)
#define MLSS_GFX1300 MLSS_GFX(1300)
#define MLSS_GFX1301 MLSS_GFX(1301)
#define MLSS_GFX1302 MLSS_GFX(1302)
#define MLSS_GFX130FFFF MLSS_GFX(130FFFF)
#define MLSS_GFX130FFFE MLSS_GFX(130FFFE)
#define MLSS_GFX130FFFD MLSS_GFX(130FFFD)
#define MLSS_GFX4000 MLSS_GFX(4000)
#define MLSS_GFX4010 MLSS_GFX(4010)
#define MLSS_GFX4020 MLSS_GFX(4020)
#define MLSS_GFX4030 MLSS_GFX(4030)
#define MLSS_GFX9_GENERIC MLSS_GFX(9_GENERIC)
#define MLSS_GFX9_4_GENERIC MLSS_GFX(9_4_GENERIC)
#define MLSS_GFX10_1_GENERIC MLSS_GFX(10_1_GENERIC)
#define MLSS_GFX10_3_GENERIC MLSS_GFX(10_3_GENERIC)
#define MLSS_GFX11_GENERIC MLSS_GFX(11_GENERIC)
#define MLSS_GFX12_GENERIC MLSS_GFX(12_GENERIC)
#define MLSS_MI400XCDML MLSS_GFX(400XCDML)
#define MLSS_MI400XCDGP MLSS_GFX(400XCDGP)
#define MLSS_GFXAUTOFIND MLSS_GFX(AUTOFIND)

#define MLSS_TAHITI MLSS(TAHITI)
#define MLSS_VERDE MLSS(VERDE)
#define MLSS_PITCAIRN MLSS(PITCAIRN)
#define MLSS_HAINAN MLSS(HAINAN)
#define MLSS_OLAND MLSS(OLAND)
#define MLSS_KAVERI MLSS(KAVERI)
#define MLSS_SPOOKY MLSS(SPOOKY)
#define MLSS_SPECTRE MLSS(SPECTRE)
#define MLSS_GRENADA MLSS(GRENADA)
#define MLSS_HAWAII MLSS(HAWAII)
#define MLSS_HAWAII_PRO MLSS(HAWAII_PRO)
#define MLSS_MULLINS MLSS(MULLINS)
#define MLSS_KABINI MLSS(KABINI)
#define MLSS_BONAIRE MLSS(BONAIRE)
#define MLSS_GODAVARI MLSS(GODAVARI)
#define MLSS_GLADIUS MLSS(GLADIUS)
#define MLSS_CARRIZO MLSS(CARRIZO)
#define MLSS_BRISTOL_RIDGE MLSS(BRISTOL_RIDGE)
#define MLSS_ICELAND MLSS(ICELAND)
#define MLSS_TONGA MLSS(TONGA)
#define MLSS_FIJI MLSS(FIJI)
#define MLSS_POLARIS10 MLSS(POLARIS10)
#define MLSS_POLARIS11 MLSS(POLARIS11)
#define MLSS_POLARIS12 MLSS(POLARIS12)
#define MLSS_POLARIS22 MLSS(POLARIS22)
#define MLSS_TONGA_PRO MLSS(TONGA_PRO)
#define MLSS_STONEY_RIDGE MLSS(STONEY_RIDGE)
#define MLSS_VEGA10 MLSS(VEGA10)
#define MLSS_GREENLAND MLSS(GREENLAND)
#define MLSS_RAVEN_RIDGE MLSS(RAVEN_RIDGE)
#define MLSS_VEGA12 MLSS(VEGA12)
#define MLSS_VEGA20 MLSS(VEGA20)
#define MLSS_ARCTURUS MLSS(ARCTURUS)
#define MLSS_MI100 MLSS(MI100)
#define MLSS_RAVEN_RIDGE2 MLSS(RAVEN_RIDGE2)
#define MLSS_ALDEBARAN MLSS(ALDEBARAN)
#define MLSS_MI200 MLSS(MI200)
#define MLSS_RENOIR MLSS(RENOIR)
#define MLSS_300A MLSS(300A)
#define MLSS_300X MLSS(300X)
#define MLSS_MI350 MLSS(MI350)
#define MLSS_ARIEL MLSS(ARIEL)
#define MLSS_NAVI10 MLSS(NAVI10)
#define MLSS_NAVI11 MLSS(NAVI11)
#define MLSS_NAVI14 MLSS(NAVI14)
#define MLSS_ROBIN MLSS(ROBIN)
#define MLSS_NAVI21 MLSS(NAVI21)
#define MLSS_SIENNA_CICHLID MLSS(SIENNA_CICHLID)
#define MLSS_NAVI22 MLSS(NAVI22)
#define MLSS_NAVI_FLOUNDER MLSS(NAVI_FLOUNDER)
#define MLSS_NAVI23 MLSS(NAVI23)
#define MLSS_DIMGREY_CAVEFISH MLSS(DIMGREY_CAVEFISH)
#define MLSS_VAN_GOGH MLSS(VAN_GOGH)
#define MLSS_NERO MLSS(NERO)
#define MLSS_NAVI24 MLSS(NAVI24)
#define MLSS_REMBRANDT MLSS(REMBRANDT)
#define MLSS_RAPHAEL MLSS(RAPHAEL)
#define MLSS_MENDOCINO MLSS(MENDOCINO)
#define MLSS_VIOLA MLSS(VIOLA)
#define MLSS_NAVI31 MLSS(NAVI31)
#define MLSS_NAVI32 MLSS(NAVI32)
#define MLSS_NAVI32GLXL MLSS(NAVI32GLXL)
#define MLSS_NAVI33 MLSS(NAVI33)
#define MLSS_NAVI34 MLSS(NAVI34)
#define MLSS_PHOENIX MLSS(PHOENIX)
#define MLSS_PHOENIX2 MLSS(PHOENIX2)
#define MLSS_NAVI3_5 MLSS(NAVI3_5)
#define MLSS_SARLAK MLSS(SARLAK)
#define MLSS_NAVI48 MLSS(NAVI48)
#define MLSS_NAVI48_A0 MLSS(NAVI48_A0)
#define MLSS_NAVI44 MLSS(NAVI44)
#define MLSS_NAVI44_A0 MLSS(NAVI44_A0)
#define MLSS_ARCADIA MLSS(ARCADIA)
#define MLSS_STRIX1_A0 MLSS(STRIX1_A0)
#define MLSS_STRIX1 MLSS(STRIX1)
#define MLSS_STRIX2 MLSS(STRIX2)
#define MLSS_STRIX3 MLSS(STRIX3)
#define MLSS_STRIXHALO MLSS(STRIXHALO)
#define MLSS_STRIX_HALO MLSS_STRIXHALO
#define MLSS_KRACKAN MLSS(KRACKAN)
#define MLSS_KRACKAN2E MLSS(KRACKAN2E)
#define MLSS_GORGONPOINT1 MLSS(GORGONPOINT1)
#define MLSS_GORGONPOINT2 MLSS(GORGONPOINT2)
#define MLSS_GORGONPOINT3 MLSS(GORGONPOINT3)
#define MLSS_GPT1 MLSS_GORGONPOINT1
#define MLSS_GPT2 MLSS_GORGONPOINT2
#define MLSS_GPT3 MLSS_GORGONPOINT3
#define MLSS_GORGON_POINT1 MLSS_GORGONPOINT1
#define MLSS_GORGON_POINT2 MLSS_GORGONPOINT2
#define MLSS_GORGON_POINT3 MLSS_GORGONPOINT3
#define MLSS_MEDUSA1_A0 MLSS(MEDUSA1_A0)
#define MLSS_MEDUSA1_B0 MLSS(MEDUSA1_B0)
#define MLSS_MEDUSA2 MLSS(MEDUSA2)
#define MLSS_MEDUSA3 MLSS(MEDUSA3)
#define MLSS_MI400_XCD_ML MLSS(400XCDML)
#define MLSS_MI400_XCD_GP MLSS(400XCDGP)
#define MLSS_AT0 MLSS(AT0)
#define MLSS_AT1 MLSS(AT1)
#define MLSS_AT2 MLSS(AT2)
#define MLSS_AT3 MLSS(AT3)
#define MLSS_ALPHA_TRION_0 MLSS_AT0
#define MLSS_ALPHA_TRION_1 MLSS_AT1
#define MLSS_ALPHA_TRION_2 MLSS_AT2
#define MLSS_ALPHA_TRION_3 MLSS_AT3
#define MLSS_CANIS MLSS(CANIS)
#define MLSS_MAGNUS MLSS(MAGNUS)
#define MLSS_ORION MLSS(ORION)
#define MLSS_MARINER MLSS(MARINER)
#define MLSS_MOBILE0 MLSS(MOBILE0)
#define MLSS_VAN_GOGH_LITE MLSS(VAN_GOGH_LITE)
#define MLSS_MOBILE1 MLSS(MOBILE1)
#define MLSS_VIKING MLSS(VIKING)
#define MLSS_MGFX1 MLSS(MGFX1)
#define MLSS_MOBILE2_EVT1_PLUS MLSS(MOBILE2_EVT1_PLUS)
#define MLSS_MOBILE2_EVT1PLUS MLSS_MOBILE2_EVT1_PLUS
#define MLSS_MOBILE3 MLSS(MOBILE3)
#define MLSS_AQUA_VANJARAM MLSS(AQUA_VANJARAM)
#define MLSS_MI300A MLSS(MI300A)
#define MLSS_MI300X MLSS(MI300X)
#define MLSS_MI325X MLSS(MI325X)

enum MLSSOPAttributesFlag
{
    MLSS_ATTR_GQA_BATCH,
    MLSS_ATTR_GQA_QSEQ,
    MLSS_ATTR_GQA_KVSEQ,
    MLSS_ATTR_GQA_KDIM,
    MLSS_ATTR_GQA_VDIM,
    MLSS_ATTR_GQA_SIZEHEADS,
    MLSS_ATTR_GQA_PACKING,
    MLSS_ATTR_GQA_QHEADCOUNT,
    MLSS_ATTR_GQA_KVHEADCOUNT,
    MLSS_ATTR_GQA_PASTSEQLENGTHSSIZE,
    MLSS_ATTR_GQA_SCALE,
    MLSS_ATTR_GQA_DATATYPE,
    MLSS_ATTR_GQA_QSTRIDES,
    MLSS_ATTR_GQA_KSTRIDES,
    MLSS_ATTR_GQA_VSTRIDES,
    MLSS_ATTR_GQA_OUTPUTSTRIDES,

    MLSS_ATTR_CONFIG_GQA_PACKING_UNPACKED,
    MLSS_ATTR_CONFIG_GQA_PACKING_PACKED_QK,
    MLSS_ATTR_CONFIG_GQA_PACKING_PACKED_KV,
    MLSS_ATTR_CONFIG_GQA_PACKING_PACKED_QKV,

    MLSS_ATTR_MHA_BATCH,
    MLSS_ATTR_MHA_QSEQ,
    MLSS_ATTR_MHA_KVSEQ,
    MLSS_ATTR_MHA_KDIM,
    MLSS_ATTR_MHA_VDIM,
    MLSS_ATTR_MHA_SIZEHEADS,
    MLSS_ATTR_MHA_PACKING,
    MLSS_ATTR_MHA_HEADCOUNT,
    MLSS_ATTR_MHA_SCALE,
    MLSS_ATTR_MHA_DATATYPE,
    MLSS_ATTR_MHA_QSTRIDES,
    MLSS_ATTR_MHA_KSTRIDES,
    MLSS_ATTR_MHA_VSTRIDES,
    MLSS_ATTR_MHA_OUTPUTSTRIDES,

    MLSS_ATTR_CONFIG_MHA_PACKING_UNPACKED,
    MLSS_ATTR_CONFIG_MHA_PACKING_PACKED_QK,
    MLSS_ATTR_CONFIG_MHA_PACKING_PACKED_KV,
    MLSS_ATTR_CONFIG_MHA_PACKING_PACKED_QKV,

    MLSS_ATTR_GEMM_M,
    MLSS_ATTR_GEMM_N,
    MLSS_ATTR_GEMM_K,
    MLSS_ATTR_GEMM_BATCH,
    MLSS_ATTR_GEMM_ALPHA,
    MLSS_ATTR_GEMM_BETA,
    MLSS_ATTR_GEMM_HASC,
    MLSS_ATTR_GEMM_TRANSA,
    MLSS_ATTR_GEMM_TRANSB,
    MLSS_ATTR_GEMM_DATATYPE,
    MLSS_ATTR_GEMM_PRECISION,
    MLSS_ATTR_GEMM_ACTIVATION,

    MLSS_ATTR_QGEMM_M,
    MLSS_ATTR_QGEMM_N,
    MLSS_ATTR_QGEMM_K,
    MLSS_ATTR_QGEMM_BATCH,
    MLSS_ATTR_QGEMM_ALPHA,
    MLSS_ATTR_QGEMM_BETA,
    MLSS_ATTR_QGEMM_HASC,
    MLSS_ATTR_QGEMM_TRANSA,
    MLSS_ATTR_QGEMM_TRANSB,
    MLSS_ATTR_QGEMM_HASASCALE,
    MLSS_ATTR_QGEMM_HASAZP,
    MLSS_ATTR_QGEMM_HASBSCALE,
    MLSS_ATTR_QGEMM_HASBZP,
    MLSS_ATTR_QGEMM_HASCSACLE,
    MLSS_ATTR_QGEMM_HASCZP,
    MLSS_ATTR_QGEMM_HASOUTSCALE,
    MLSS_ATTR_QGEMM_HASOUTZP,
    MLSS_ATTR_QGEMM_QRATIOBSCALE,
    MLSS_ATTR_QGEMM_QRATIOBZP,
    MLSS_ATTR_QGEMM_DATATYPEA,
    MLSS_ATTR_QGEMM_DATATYPEB,
    MLSS_ATTR_QGEMM_DATATYPEC,
    MLSS_ATTR_QGEMM_DATATYPEOUTPUT,
    MLSS_ATTR_QGEMM_DATATYPEQPARAMSA,
    MLSS_ATTR_QGEMM_DATATYPEQPARAMSB,
    MLSS_ATTR_QGEMM_DATATYPEQPARAMSC,
    MLSS_ATTR_QGEMM_DATATYPEQPARAMSOUTPUT,
    MLSS_ATTR_QGEMM_PRECISION,
    MLSS_ATTR_QGEMM_ACTIVATION,

    MLSS_ATTR_MVN_N,
    MLSS_ATTR_MVN_C,
    MLSS_ATTR_MVN_H,
    MLSS_ATTR_MVN_W,
    MLSS_ATTR_MVN_EPSILON,
    MLSS_ATTR_MVN_CROSSCHANNEL,
    MLSS_ATTR_MVN_SBDIMS,
    MLSS_ATTR_MVN_HASSCALE,
    MLSS_ATTR_MVN_HASBIAS,
    MLSS_ATTR_MVN_DATATYPE,
    MLSS_ATTR_MVN_ACTIVATION,

    MLSS_ATTR_CONV_W,
    MLSS_ATTR_CONV_H,
    MLSS_ATTR_CONV_C,
    MLSS_ATTR_CONV_N,
    MLSS_ATTR_CONV_K,
    MLSS_ATTR_CONV_S,
    MLSS_ATTR_CONV_R,
    MLSS_ATTR_CONV_OUTW,
    MLSS_ATTR_CONV_OUTH,
    MLSS_ATTR_CONV_DILATIONX,
    MLSS_ATTR_CONV_DILATIONY,
    MLSS_ATTR_CONV_STARTPADX,
    MLSS_ATTR_CONV_STARTPADY,
    MLSS_ATTR_CONV_ENDPADX,
    MLSS_ATTR_CONV_ENDPADY,
    MLSS_ATTR_CONV_OUTPADX,
    MLSS_ATTR_CONV_OUTPADY,
    MLSS_ATTR_CONV_CONVSTRIDEX,
    MLSS_ATTR_CONV_CONVSTRIDEY,
    MLSS_ATTR_CONV_INPUTSTRIDEX,
    MLSS_ATTR_CONV_INPUTSTRIDEY,
    MLSS_ATTR_CONV_FILTERSTRIDEX,
    MLSS_ATTR_CONV_FILTERSTRIDEY,
    MLSS_ATTR_CONV_GROUPS,
    MLSS_ATTR_CONV_HASBIAS,
    MLSS_ATTR_CONV_CROSSCORRELATION,
    MLSS_ATTR_CONV_BACKWARD,
    MLSS_ATTR_CONV_DNSTRIDE,
    MLSS_ATTR_CONV_DHSTRIDE,
    MLSS_ATTR_CONV_DCSTRIDE,
    MLSS_ATTR_CONV_FKSTRIDE,
    MLSS_ATTR_CONV_FCSTRIDE,
    MLSS_ATTR_CONV_FRSTRIDE,
    MLSS_ATTR_CONV_FSSTRIDE,
    MLSS_ATTR_CONV_ONSTRIDE,
    MLSS_ATTR_CONV_OHSTRIDE,
    MLSS_ATTR_CONV_OKSTRIDE,
    MLSS_ATTR_CONV_DOFFSET,
    MLSS_ATTR_CONV_OOFFSET,
    MLSS_ATTR_CONV_FOFFSET,
    MLSS_ATTR_CONV_BOFFSET,
    MLSS_ATTR_CONV_DATATYPE,
    MLSS_ATTR_CONV_PRECISION,
    MLSS_ATTR_CONV_ACTIVATION,

    MLSS_ATTR_CONV_DILATED_W,
    MLSS_ATTR_CONV_DILATED_H,
    MLSS_ATTR_CONV_DILATED_C,
    MLSS_ATTR_CONV_DILATED_N,
    MLSS_ATTR_CONV_DILATED_K,
    MLSS_ATTR_CONV_DILATED_S,
    MLSS_ATTR_CONV_DILATED_R,
    MLSS_ATTR_CONV_DILATED_OUTW,
    MLSS_ATTR_CONV_DILATED_OUTH,
    MLSS_ATTR_CONV_DILATED_STARTPADX,
    MLSS_ATTR_CONV_DILATED_STARTPADY,
    MLSS_ATTR_CONV_DILATED_ENDPADX,
    MLSS_ATTR_CONV_DILATED_ENDPADY,
    MLSS_ATTR_CONV_DILATED_OUTPADX,
    MLSS_ATTR_CONV_DILATED_OUTPADY,
    MLSS_ATTR_CONV_DILATED_CONVSTRIDEX,
    MLSS_ATTR_CONV_DILATED_CONVSTRIDEY,
    MLSS_ATTR_CONV_DILATED_INPUTSTRIDEX,
    MLSS_ATTR_CONV_DILATED_INPUTSTRIDEY,
    MLSS_ATTR_CONV_DILATED_FILTERSTRIDEX,
    MLSS_ATTR_CONV_DILATED_FILTERSTRIDEY,
    MLSS_ATTR_CONV_DILATED_GROUPS,
    MLSS_ATTR_CONV_DILATED_HASBIAS,
    MLSS_ATTR_CONV_DILATED_CROSSCORRELATION,
    MLSS_ATTR_CONV_DILATED_BACKWARD,
    MLSS_ATTR_CONV_DILATED_DNSTRIDE,
    MLSS_ATTR_CONV_DILATED_DHSTRIDE,
    MLSS_ATTR_CONV_DILATED_DCSTRIDE,
    MLSS_ATTR_CONV_DILATED_FKSTRIDE,
    MLSS_ATTR_CONV_DILATED_FCSTRIDE,
    MLSS_ATTR_CONV_DILATED_FRSTRIDE,
    MLSS_ATTR_CONV_DILATED_FSSTRIDE,
    MLSS_ATTR_CONV_DILATED_ONSTRIDE,
    MLSS_ATTR_CONV_DILATED_OHSTRIDE,
    MLSS_ATTR_CONV_DILATED_OKSTRIDE,
    MLSS_ATTR_CONV_DILATED_DOFFSET,
    MLSS_ATTR_CONV_DILATED_OOFFSET,
    MLSS_ATTR_CONV_DILATED_FOFFSET,
    MLSS_ATTR_CONV_DILATED_BOFFSET,
    MLSS_ATTR_CONV_DILATED_DATATYPE,
    MLSS_ATTR_CONV_DILATED_PRECISION,
    MLSS_ATTR_CONV_DILATED_ACTIVATION,

    MLSS_ATTR_RMSNORM_M,
    MLSS_ATTR_RMSNORM_N,
    MLSS_ATTR_RMSNORM_DATATYPE,

    MLSS_ATTR_SIGMOID_MUL_N,
    MLSS_ATTR_SIGMOID_MUL_C,
    MLSS_ATTR_SIGMOID_MUL_H,
    MLSS_ATTR_SIGMOID_MUL_W,
    MLSS_ATTR_SIGMOID_MUL_DATATYPE,

    MLSS_ATTR_GEMMGEMM_M,
    MLSS_ATTR_GEMMGEMM_N,
    MLSS_ATTR_GEMMGEMM_K,
    MLSS_ATTR_GEMMGEMM_L,
    MLSS_ATTR_GEMMGEMM_BATCH,
    MLSS_ATTR_GEMMGEMM_DATATYPE,
    MLSS_ATTR_GEMMGEMM_QUANTDATATYPE,
    MLSS_ATTR_GEMMGEMM_TRANSB0,
    MLSS_ATTR_GEMMGEMM_TRANSB1,
};

enum MLSSPrecisionFlag
{
    MLSS_PRECISION_FLOAT32,
    MLSS_PRECISION_FLOAT16,
    MLSS_PRECISION_FLOAT16_ADD_FLOAT32,
    MLSS_PRECISION_COUNT
};

enum MLSSActivationFunctionFlag
{
    MLSS_ACTIVATION_ELU,
    MLSS_ACTIVATION_HARDMAX,
    MLSS_ACTIVATION_HARD_SIGMOID,
    MLSS_ACTIVATION_IDENTITY,
    MLSS_ACTIVATION_LEAKY_RELU,
    MLSS_ACTIVATION_LINEAR,
    MLSS_ACTIVATION_LOG_SOFTMAX,
    MLSS_ACTIVATION_PARAMETERIZED_RELU,
    MLSS_ACTIVATION_PARAMETRIC_SOFTPLUS,
    MLSS_ACTIVATION_RELU,
    MLSS_ACTIVATION_SCALED_ELU,
    MLSS_ACTIVATION_SCALED_TANH,
    MLSS_ACTIVATION_SIGMOID,
    MLSS_ACTIVATION_SOFTMAX,
    MLSS_ACTIVATION_SOFTPLUS,
    MLSS_ACTIVATION_SOFTSIGN,
    MLSS_ACTIVATION_TANH,
    MLSS_ACTIVATION_THRESHOLDED_RELU,
    MLSS_ACTIVATION_COUNT
};

enum MLSSDeviceTypesFlag
{
    MLSS_DEVICE_APU,
    MLSS_DEVICE_dGPU,
    MLSS_DEVICE_gGPU,
    MLSS_DEVICE_UNKNOWN
};

enum MLSSTypesFlag
{
    MLSS_SHIFT_MASK = 0x10,
    MLSS_NONE_TYPE = 0 << MLSS_SHIFT_MASK,
    MLSS_VOID = MLSS_NONE_TYPE,
    MLSS_BOOL = 1 << MLSS_SHIFT_MASK,
    MLSS_INT4 = 2 << MLSS_SHIFT_MASK,
    MLSS_UINT4 = 3 << MLSS_SHIFT_MASK,
    MLSS_INT8 = 4 << MLSS_SHIFT_MASK,
    MLSS_UINT8 = 5 << MLSS_SHIFT_MASK,
    MLSS_INT16 = 6 << MLSS_SHIFT_MASK,
    MLSS_UINT16 = 7 << MLSS_SHIFT_MASK,
    MLSS_INT32 = 8 << MLSS_SHIFT_MASK,
    MLSS_UINT32 = 9 << MLSS_SHIFT_MASK,
    MLSS_INT64 = 10 << MLSS_SHIFT_MASK,
    MLSS_UINT64 = 11 << MLSS_SHIFT_MASK,
    MLSS_FLOAT4 = 12 << MLSS_SHIFT_MASK,
    MLSS_FLOAT8 = 13 << MLSS_SHIFT_MASK,
    MLSS_FLOAT8_FNUZ = 14 << MLSS_SHIFT_MASK,
    MLSS_FLOAT8_OCP = 15 << MLSS_SHIFT_MASK,
    MLSS_FLOAT16 = 16 << MLSS_SHIFT_MASK,
    MLSS_FLOAT32 = 17 << MLSS_SHIFT_MASK,
    MLSS_FLOAT64 = 18 << MLSS_SHIFT_MASK,
    MLSS_BFLOAT4 = 19 << MLSS_SHIFT_MASK,
    MLSS_BFLOAT8 = 20 << MLSS_SHIFT_MASK,
    MLSS_BFLOAT8_FNUZ = 21 << MLSS_SHIFT_MASK,
    MLSS_BFLOAT8_OCP = 22 << MLSS_SHIFT_MASK,
    MLSS_BFLOAT16 = 23 << MLSS_SHIFT_MASK,
    MLSS_ENUM = 24 << MLSS_SHIFT_MASK,
    MLSS_ENUM64 = 25 << MLSS_SHIFT_MASK,
    MLSS_CONTEXT = 26 << MLSS_SHIFT_MASK,
    MLSS_ARG = 27 << MLSS_SHIFT_MASK,
    MLSS_VECTOR = 28 << MLSS_SHIFT_MASK,
    MLSS_DIM3 = 29 << MLSS_SHIFT_MASK,
    MLSS_BINARY = 30 << MLSS_SHIFT_MASK,
    MLSS_STRING = 31 << MLSS_SHIFT_MASK,
    MLSS_UNKNOWN_TYPE = 32 << MLSS_SHIFT_MASK,
    MLSS_CUSTOM_TYPE = 33 << MLSS_SHIFT_MASK,
    MLSS_UNSET_TYPE = 34 << MLSS_SHIFT_MASK,
    MLSS_ARRAY = 0x80000000,
    MLSS_TYPE_MASK = 0x00FFFFF0,
    MLSS_CUSTOM_TYPE_START = 0x01000000 // Start of custom type ID range
};

enum MLSSStatusFlag
{
    MLSS_SUCCESS = 0,
    MLSS_ERROR_FAILURE = 1,
    MLSS_ERROR_CONFIGURATION_NOT_SUPPORTED = 2,
    MLSS_ERROR_GRAPHIX_NOT_SUPPORTED = 3,
    MLSS_ERROR_OPERATOR_NOT_SUPPORTED = 4,
    MLSS_ERROR_INVALID_PARAMETER = 5,
    MLSS_ERROR_PARAMETER_NOT_FOUND = 6,
    MLSS_ERROR_OPERATOR_NOT_FOUND = 7,

    // Dynamic Load Errors (1-99)
    MLSS_ERROR_DYNAMIC_LOAD_LIBRARY_NOT_FOUND = 10,
    MLSS_ERROR_DYNAMIC_LOAD_SYMBOL_NOT_FOUND = 11,
    MLSS_ERROR_DYNAMIC_LOAD_UNDEFINED_SYMBOL = 12,
    MLSS_ERROR_DYNAMIC_LOAD_PERMISSION_DENIED = 13,
    MLSS_ERROR_DYNAMIC_LOAD_INVALID_ELF = 14,

    // Environment Errors (100-199)
    MLSS_ERROR_ENVIRONMENT_VARIABLE_NOT_FOUND = 100,
    MLSS_ERROR_ENVIRONMENT_INVALID_PATH = 101,
    MLSS_ERROR_ENVIRONMENT_PATH_NOT_EXISTS = 102,
    MLSS_ERROR_ENVIRONMENT_ACCESS_DENIED = 103,
    MLSS_ERROR_ENVIRONMENT_BUFFER_TOO_SMALL = 104,
    MLSS_ERROR_ENVIRONMENT_INVALID_ARGUMENT = 105,

    // Device Query Errors (200-299)
    MLSS_ERROR_DEVICE_QUERY_HIP_RUNTIME_ERROR = 200,
    MLSS_ERROR_DEVICE_QUERY_NO_DEVICES_FOUND = 201,
    MLSS_ERROR_DEVICE_QUERY_NO_SUPPORTED_DEVICES_FOUND = 202,

    // Shader Errors (300-399)
    MLSS_ERROR_SHADER_UNSUPPORTED_ARCHITECTURE = 300,
    MLSS_ERROR_SHADER_UNSUPPORTED_CONFIGURATION = 301,
    MLSS_ERROR_SHADER_UNSUPPORTED_OPERATOR = 302,
    MLSS_ERROR_SHADER_INVALID_PARAMETERS = 303,
    MLSS_ERROR_SHADER_FEATURE_NOT_YET_IMPLEMENTED = 304,

    // Enums Errors (400-499)
    MLSS_ERROR_ENUM_CODENAME_NOT_FOUND = 400,
    MLSS_ERROR_ENUM_ARCHITECTURE_NOT_FOUND = 401,
    MLSS_ERROR_ENUM_ARCHITECTURE_NOT_SUPPORTED = 402,
    MLSS_ERROR_ENUM_ELF_MATCH_NOT_FOUND = 403,

    // Unknown error
    MLSS_ERROR_UNKNOWN_ERROR = 999,

    // General Errors (1000+)
    MLSS_ERROR_BAD_MEMORY_ALLOCATION = 1000,
    MLSS_ERROR_ALREADY_EXISTING_CONTEXT = 1001,
    MLSS_ERROR_CONTEXT_NOT_CREATED = 1002,
    MLSS_ERROR_FAILED_TO_CREATE_CONTEXT = 1003,
    MLSS_ERROR_NOT_IMPLEMENTED = 1004,
    MLSS_ERROR_INVALID_FEATURE = 1005,
    MLSS_ERROR_INVALID_SETTING = 1006,
    MLSS_ERROR_CONTEXT_UPDATE_FAILED = 1007,
    MLSS_ERROR_UNKNOWN_ATTRIBUTE = 1008,

    MLSS_WARNING_CONTEXT_ALREADY_EXISTING = 1100,
    MLSS_WARNING_NOT_IMPLEMENTED = 1101
};




// Legacy verbose levels for backward compatibility
enum MLSSVerboseLegacy
{
    MLSS_VERBOSE_NONE = 0,
    MLSS_VERBOSE_LEVEL_ERROR = 1,
    MLSS_VERBOSE_LEVEL_WARNING = 2,
    MLSS_VERBOSE_LEVEL_INFO = 3,
    MLSS_VERBOSE_LEVEL_DEBUG = 4
};

// Basic type definitions
typedef bool MLSSbool;
typedef int8_t MLSSint8;
typedef uint8_t MLSSuint8;
typedef int16_t MLSSint16;
typedef uint16_t MLSSuint16;
typedef int32_t MLSSint32;
typedef uint32_t MLSSuint32;
typedef int64_t MLSSint64;
typedef uint64_t MLSSuint64;
typedef float MLSSfloat32;
typedef double MLSSfloat64;
typedef uint32_t MLSSstatus;
typedef uint32_t MLSSenum;
typedef char MLSSchar;
typedef char* MLSSstring;
typedef const char* MLSSconststring;
typedef char** MLSSstringarray;
typedef char** MLSSstringref;
typedef char*** MLSSstringarrayref;
typedef void MLSSvoid;
typedef size_t MLSSsize;
typedef MLSSuint64 MLSShandle;
typedef MLSShandle MLSScontext;
typedef size_t MLSSsize;

typedef struct
{
    MLSSuint32 m_x, m_y, m_z;

} MLSSdim3;

typedef struct
{
    MLSSint32 m_place;
    MLSSenum m_type;
    MLSSbool m_isPointer;
    MLSSuint32 m_indirectionLevel;
    MLSSbool m_isConst;
    MLSSbool m_isInput;
    MLSSbool m_isReturn;
    MLSSconststring m_name;

} MLSSarg;

typedef struct
{
    MLSSsize m_size;
    MLSSenum m_type;
    MLSShandle m_handle;

} MLSSvector;

typedef struct
{
    MLSSstring m_pOperatorName;
    MLSSstring m_ASIC;
    MLSSstring m_pKernelName;

    MLSSdim3 m_grid;
    MLSSdim3 m_blocks;
    MLSSuint64 m_sharedMemInBytes;

    MLSSvector m_constants;

    MLSSvector m_argList;
    MLSSvoid* m_binaries;
    MLSSsize m_binarySize;
    MLSSenum m_type;

    MLSSbool m_isRelocatable;

} MLSSbinary;

// Filter passed to mlssGetBinariesEx to select which ELF variant is returned.
// MLSS emits two blobs per kernel: a relocatable object (.o) from the shader
// archive and a linked executable produced by amd_comgr.
typedef enum
{
    MLSS_BINARY_KIND_NON_RELOCATABLE = 0, // Linked executable — loadable by hipModuleLoadData (default)
    MLSS_BINARY_KIND_RELOCATABLE     = 1, // Raw relocatable ELF — for callers that link themselves
    MLSS_BINARY_KIND_ANY             = 2, // All valid blobs regardless of ELF type
} MLSSbinaryKind;

typedef struct
{
    MLSSuint32 m_numCUs;
    MLSSuint32 m_sizeShaderMem;
    MLSSconststring m_gfx;
    MLSSbool m_isDedicated;
    MLSSuint32 m_gpuIdx;

} MLSSdevicefeatures;

// Custom Type Support

// Context functions - for setting/getting parameters in MLSS context
typedef MLSSstatus (*MLSScustomtypeset)(MLSScontext* context, const MLSSchar* opName, const MLSSvoid* data);
typedef MLSSstatus (*MLSScustomtypeget)(const MLSScontext context, const MLSSchar* opName, MLSSvoid** data);

// Print function - for displaying custom type details
typedef MLSSvoid (*MLSScustomtypeprint)(const MLSSvoid* data);

// Custom type information structure
typedef struct
{
    MLSSconststring m_typeName;
    MLSSenum m_typeId;
    MLSScustomtypeset m_setFunc;
    MLSScustomtypeget m_getFunc;
    MLSScustomtypeprint m_printFunc;
    MLSSstringarray m_supportedOperators; // NULL-terminated array
} MLSScustomtypeinfo;
